#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_ENABLE_DEBUGGER

#define CONFIG_ENABLE_M_EXTENSION
#define CONFIG_ENABLE_A_EXTENSION
// #define CONFIG_ENABLE_C_EXTENSION

#define CONFIG_ENABLE_ZICSR_EXTENSION
#define CONFIG_ENABLE_ZIFENCEI_EXTENSION

#define CONFIG_ENABLE_UART_DEVICE

#endif
